#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"

PID_PATH=/var/run/my_process.pid

start()
{
	./manage_my_process &
	echo "$!" > "$PID_PATH"
}
restart()
{
	./manage_my_process &
	rm -rf "$PID_PATH"
	echo "$!" > "$PID_PATH"
}
stop()
{
	sudo kill -15 "$(cat "$PID_PATH")" &&
	rm -f "$PID_PATH"
}

case "$1" in
	start)
		start
		echo "manage_my_process started"
		;;
	restart)
		restart
		echo "manage_my_process restarted"
		;;
	stop)
		stop
		echo "manage_my_process stopped"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac

exit 0
